# Generated by Django 2.2.5 on 2019-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myshippingAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdemailid', models.CharField(default='', max_length=254)),
                ('pAddressLine1', models.CharField(max_length=100)),
                ('pAddressLine2', models.CharField(max_length=100)),
                ('pCity', models.CharField(max_length=100)),
                ('pState', models.CharField(max_length=100)),
                ('pZip', models.IntegerField()),
                ('dAddressLine1', models.CharField(max_length=100)),
                ('dAddressLine2', models.CharField(max_length=100)),
                ('dCity', models.CharField(max_length=100)),
                ('dState', models.CharField(max_length=100)),
                ('dZip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='myuserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udemailid', models.CharField(default='', max_length=254)),
                ('phoneNumber', models.IntegerField()),
                ('ageOfChild', models.IntegerField()),
                ('genderOfChild', models.CharField(max_length=1)),
                ('memType', models.CharField(max_length=1)),
                ('invalid', models.CharField(max_length=1)),
            ],
        ),
    ]
